# Generated by Django 4.1.3 on 2022-12-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
