# Generated by Django 4.1.3 on 2022-12-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_logindata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='', upload_to='app/static/'),
        ),
    ]
